FROM python:3.6
LABEL maintainer 'Diego Schmitz'

RUN useradd www && \
    mkdir /app && \
    mkdir /log && \
    chown www /log

USER www
VOLUME /log
WORKDIR /app
EXPOSE 8082

ENTRYPOINT ["/usr/local/bin/python"]
CMD ["run.py"]